#!/bin/bash
echo "Welcome $USER "
echo "#To use this run it with
curl -sSL https://git.aevl.net/tek/umupdate/raw/branch/main/friendica-update | bash
"
sleep 3
bash <(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/friendica-update)
