#!/bin/bash
echo "ArchLinux Kernel check for Linux-Zen"
uname -a
echo "Hello " $USER "@" $HOSTNAME

running_kernel=$(uname -r | sed 's/-zen$//;s/-/./')
installed_kernel=$(pacman -Qi linux-zen | awk '/Version/ {print $3}')
uptime=$(uptime -p)

echo "Running Kernel: $running_kernel"
echo "Installed Kernel: $installed_kernel"
echo "System Uptime: $uptime"

function version_compare() {
    if [[ $1 == $2 ]]; then
        echo "equal"
    elif [[ $1 < $2 ]]; then
        echo "less than"
    else
        echo "greater than"
    fi
}

comparison_result=$(version_compare "$running_kernel" "$installed_kernel")

echo "Comparison Result: $comparison_result"

if [[ "$comparison_result" != "equal" ]]; then
    echo "Running kernel does not match the installed kernel."
    echo "It is recommended to reboot the system."
elif [[ $uptime == *"day"* ]]; then
    days=$(echo $uptime | awk '{print $2}')
    if (( days > 6 )); then
        echo "Running kernel matches installed kernel, but the system has been running for more than 6 days."
        echo "It is recommended to reboot the system."
    else
        echo "Running kernel matches installed kernel and the system has been running for less than 6 days."
        echo "No reboot is necessary at this time."
    fi
else
    echo "Running kernel matches installed kernel and the system has been running for less than 6 days."
    echo "No reboot is necessary at this time."
fi
