#!/bin/bash
# Function to check if Pi-hole is installed and running on a host
function check_pihole {
  # Check if the Pi-hole service is running
  if ssh -q -o ConnectTimeout=1 $1 "systemctl is-active pihole-FTL.service &> /dev/null"; then
    # Check if the Pi-hole web interface is accessible
    if curl -s -I -H "Host: pi.hole" http://$1/admin/ &> /dev/null; then
      return 0  # Pi-hole is installed and running
    fi
  fi
  return 1  # Pi-hole is not installed or not running
}

# Retrieve IP addresses from ARP table
arp_ip_list=$(arp -a | awk '{print $2}' | sed 's/[()]//g')

# Combine the IP lists
ip_list="$arp_ip_list"

# Iterate over each IP address and perform SSH connection
for ip in $ip_list; do
    # Perform SSH connection to the device
    echo "Connecting to $ip"
    if check_pihole $ip; then
      echo "Pi-hole detected on $IP"
      ssh -y -X $ip "bash <(curl -s https://raw.githubusercontent.com/tek-aevl/umupdate/main/rpi-update)"
    else
      ssh -ty -X $ip "bash <(curl -s https://raw.githubusercontent.com/tek-aevl/umupdate/main/debupdate)"
    fi
done
